# Generated by Django 3.2.13 on 2022-06-30 14:47

from django.db import migrations, models
import rr.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('html', models.TextField(default='<div></div>')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreFooterSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('content', rr.fields.RoadRunnerField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('content', rr.fields.RoadRunnerField()),
            ],
            options={
                'ordering': ['name'],
            }
        ),
    ]
