# Generated by Django 3.2.13 on 2022-09-27 14:58

from django.db import migrations
import rr.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='PreFooterSnippet',
        ),
        migrations.AlterField(
            model_name='template',
            name='content',
            field=rr.fields.RoadRunnerField(blank=True, null=True),
        ),
    ]
