# Generated by Django 4.2.11 on 2024-03-27 13:56

from django.db import migrations
import rr.fields


class Migration(migrations.Migration):

    dependencies = [
        ("rr", "0002_auto_20220927_1658"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="content",
            field=rr.fields.RoadRunnerField(blank=True, null=True, use_json_field=True),
        ),
    ]
