# Generated by Django 2.1.5 on 2019-01-30 16:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadrunner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naam')),
                ('html', models.TextField(default='<div></div>')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('block_type', models.CharField(choices=[('char', 'Tekst'), ('richtext', 'Richtext'), ('text', 'Meerdere regels tekst'), ('image', 'Afbeelding'), ('page', 'Pagina'), ('document', 'Document'), ('choice', 'Dropdown'), ('multiple_choice', 'Meerdere keuze dropdown'), ('integer', 'Nummer'), ('date', 'Datum'), ('boolean', 'Checkbox'), ('color', 'Kleur'), ('email', 'Email'), ('url', 'URL')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Bij dropdowns/multi-dropdowns', verbose_name='choices')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('block', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='roadrunner.Block')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
