# Generated by Django 2.1.5 on 2019-01-31 08:14

from django.db import migrations, models
import roadrunner.blocks
import roadrunner.fields
import wagtail.core.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('roadrunner', '0002_block_blockfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naam')),
                ('content', roadrunner.fields.RoadRunnerField())
            ],
        ),
    ]
