# Generated by Django 3.2.12 on 2022-02-10 09:50
import json
from django.db import migrations
from roadrunner.utils import fix_json

def forward(apps, schema_editor):
    Template = apps.get_model("roadrunner", "Template")
    for row in Template.objects.all():
        try:
            data = list(row.content.raw_data)
            fixed_data = fix_json(data)
            row.content = json.dumps(fixed_data)
            row.save()
        except TypeError:
            pass

    PreFooterSnippet = apps.get_model("roadrunner", "PreFooterSnippet")
    for row in Template.objects.all():
        try:
            data = list(row.content.raw_data)
            fixed_data = fix_json(data)
            row.content = json.dumps(fixed_data)
            row.save()
        except TypeError:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('roadrunner', '0003_template'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
